# Alacritty configuration
# ArseLinuxOS

[window]
padding = { x = 5, y = 5 }
decorations = "full"
opacity = 0.95

[font]
size = 11.0

[font.normal]
family = "Hack"
style = "Regular"

[font.bold]
family = "Hack"
style = "Bold"

[font.italic]
family = "Hack"
style = "Italic"

[colors.primary]
background = "#0d181a"
foreground = "#cbdcdb"

[colors.normal]
black   = "#0d181a"
red     = "#4f7a84"
green   = "#677e82"
yellow  = "#59858e"
blue    = "#669198"
magenta = "#75a1a7"
cyan    = "#8bb2b5"
white   = "#cbdcdb"

[colors.bright]
black   = "#8e9a99"
red     = "#4f7a84"
green   = "#677e82"
yellow  = "#59858e"
blue    = "#669198"
magenta = "#75a1a7"
cyan    = "#8bb2b5"
white   = "#cbdcdb"

[cursor]
style = { shape = "Block", blinking = "Off" }

[selection]
save_to_clipboard = true
